target 'ACEOAuth2RACManagerDemo' do
	pod 'AFOAuth2Manager', '~> 2.2'
	pod 'AFNetworkActivityLogger', '~> 2.0'
	pod 'AFNetworking-RACRetryExtensions', '~> 0.2'
    pod 'NSURL+QueryDictionary', '~> 1.1'
end