target 'ACEOAuth2RACManagerDemo' do
    pod 'ACEOAuth2RACManager', :subspecs => [
        'AFNetworkActivityLogger',
        'AFNetworking-RACRetryExtensions',
        'CocoaLumberjack',
    ], :path => '../'
end

target 'Today' do
    pod 'ACEOAuth2RACManager', :subspecs => [
        'AFNetworkActivityLogger',
        'AFNetworking-RACRetryExtensions',
        'CocoaLumberjack',
    ], :path => '../'
end
